import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
process.env.INVENTORY_DB_PATH=path.join(mkdtempSync(path.join(tmpdir(),'orc-security-db-')),'inventory.db');
process.env.INVENTORY_PASSWORD='synthetic-password-for-disposable-tests';
process.env.CRVMGMT_SECRET='synthetic-signing-secret-for-disposable-tests';
test('real SQLite role boundaries, revocation and login quotas',async()=>{
 const users=await import('../src/lib/inventory/users');
 const owner=users.listUsers()[0];
 assert.throws(()=>users.createUser({username:'bad',name:'bad',role:'superadmin',password:'test-password'},'admin'));
 assert.throws(()=>users.resetPassword(owner.id,'test-password','admin'));
 const user=users.createUser({username:'worker',name:'worker',role:'admin',password:'test-password'},'superadmin');
 const {createSession}=await import('../src/lib/inventory/session');
 const {readSession}=await import('../src/lib/inventory/session-server');
 const token=await createSession(user.id,user.role,user.session_version);
 assert.ok(await readSession(token));
 users.resetPassword(user.id,'replacement-password','superadmin');
 assert.equal(await readSession(token),null);
 const {loginAllowed}=await import('../src/lib/inventory/login-rate-limit');
 for(let i=0;i<5;i++)assert.equal(loginAllowed('synthetic-user'),true);
 assert.equal(loginAllowed('synthetic-user'),false);
 const {getDb}=await import('../src/lib/inventory/db');const db=getDb();
 for(let i=0;i<25;i++)db.prepare('INSERT INTO orc_login_limits(key,count,reset_at) VALUES (?,1,?)').run(`expired-${i}`,Date.now()-7200000);
 assert.equal(loginAllowed('synthetic-user'),false);
 assert.equal((db.prepare('SELECT count(*) AS count FROM orc_login_limits').get() as {count:number}).count,7,'cleanup removes at most twenty expired counters');
 db.prepare("UPDATE orc_login_limits SET count=100 WHERE key='global'").run();
 for(let i=0;i<50;i++)assert.equal(loginAllowed(`rotating-user-${i}`),false);
 assert.equal((db.prepare('SELECT count(*) AS count FROM orc_login_limits').get() as {count:number}).count,2,'global rejection never stores new attacker-controlled account keys');
});
